import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function TopNav() {
  return  (
    <nav className="w-full flex items-center justify-between p-4 text-x1 font-semibold border-b">
      <div>Gallery</div>
      <div>Sign In</div>
    </nav>
  );}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} flex flex-col gap-4`}>
        <TopNav/>
        {children}
      </body>
    </html>
  );
}
